name: 2015 ISL study
#description: 통계 공부 정리
meta_description: "통계 스터디 정리용 블로그"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /study_isl
domain_name: 'http://gladtosee.github.io/kasper'
#google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url: 'http://gladtosee.github.io/kasper'
author: 'gladtosee'
